spring:
  application:
    name: library-management

  data:
    mongodb:
      uri: mongodb://localhost:27017/library_db

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always